version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "quietavenue-dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1x27nddmanbga"
s3_prefix = "quietavenue-dev" #Same name that "BucketName" in resources.yaml
region = "us-west-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"

[production]
[production.deploy]
[production.deploy.parameters]
stack_name = "quietavenue"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1x27nddmanbga"
s3_prefix = "quietavenue"
region = "us-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"