export const FETCH_PROPERTIES_SUCCEEDED = "FETCH_PROPERTIES_SUCCEEDED";
export const FETCH_FILTER_PROPERTIES_SUCCEEDED = "FETCH_FILTER_PROPERTIES_SUCCEEDED";
export const FETCH_PROPERTY_SUCCEEDED = "FETCH_PROPERTY_SUCCEEDED";
export const FETCH_SEARCH_INPUT_SUCCEDED = "FETCH_SEARCH_INPUT_SUCCEDED";

export const FETCH_STARTED = "FETCH_STARTED";
export const FETCH_FAILED = "FETCH_FAILED";

export const SEARCH_INPUT_CHANGED = "SEARCH_INPUT_CHANGED";