export const FETCH_ESTATES_SUCCEEDED = "FETCH_ESTATES_SUCCEEDED";
export const FETCH_ESTATE_SUCCEEDED = "FETCH_ESTATE_SUCCEEDED";

export const FETCH_STARTED = "FETCH_STARTED";
export const FETCH_FAILED = "FETCH_FAILED";
