export const FETCH_PROPERTIES_SUCCEEDED = 'FETCH_PROPERTIES_SUCCEEDED';
export const FETCH_PROPERTIES_FAILED = 'FETCH_PROPERTIES_FAILED';
export const FETCH_PROPERTY_SUCCEEDED = 'FETCH_PROPERTY_SUCCEEDED';
export const PROPERTY_NOT_FOUND = 'PROPERTY_NOT_FOUND';
export const FETCH_PROPERTY_FAILED = 'FETCH_PROPERTY_FAILED';